version: "2"
services:
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Password!12"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$${SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  myapp-app:
    build:
      context: ../
      dockerfile: Dockerfile-Back
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:80
